sGrades/Controllers/CoursesController.cs
using sGrades.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sGrades.Controllers
{
    [RoleAuthorization(Roles = "Lecturer")]

    public class CoursesController : Controller
    {
        // GET: Courses
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult New()
        {
            return View();
        }

        public ActionResult Edit(int Id)
        {
            return View("Edit",model:Id);
        }
        public ActionResult Details(int Id)
        {
            return View("Details", model: Id);
        }

        public ActionResult Enroll(int Id)
        {
            return View("Enroll", model: Id);
        }

        public ActionResult NewAssignment(int Id)
        {
            return View("NewAssignment", model: Id);
        }

        public ActionResult EditAssignment(int Id)
        {
            return View("EditAssignment", model: Id);
        }

        public ActionResult Grades(int Id)
        {
            return View("Grades", model: Id);
        }
    }
}

sGrades/Controllers/StudentCoursesController.cs
using sGrades.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sGrades.Controllers
{
    [RoleAuthorization(Roles = "Student")]
    public class StudentCoursesController : Controller
    {
        // GET: StudentCourses
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Grades(int id)
        {
            return View("Grades",model:id);
        }
    }
}

sGrades/Controllers/StudentsController.cs
using Microsoft.AspNet.Identity;
using sGrades.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace sGrades.Controllers
{
    [RoleAuthorization(Roles ="Lecturer")]
    public class StudentsController : Controller
    {

        private ApplicationDbContext _context;


        public StudentsController()
        {
            _context = new ApplicationDbContext();

            
        }

        private string GetUserName()
        {
            var currUserId = User.Identity.GetUserId();
            var currUser = _context.Users.Single(c => c.Id.Equals(currUserId));
            return currUser.UserName;
        }

        // GET: Students

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(string id)
        {

            return View("Edit",model:id);
        }
    }
}

sGrades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - S-Grades</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Lecturer"))
                {
                    @Html.ActionLink("S-Grades", "Index", "Courses", new { area = "" }, new { @class = "navbar-brand" })

                }
                else
                {
                    if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
                    {
                        @Html.ActionLink("S-Grades", "Index", "StudentCourses", new { area = "" }, new { @class = "navbar-brand" })
                    }
                    else
                    {
                        @Html.ActionLink("S-Grades", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    }
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Student"))
                    {
                         <li>@Html.ActionLink("My Courses And Grades", "Index", "StudentCourses")</li>
                    }
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Lecturer"))
                    {
                        <li>@Html.ActionLink("My Students", "Index", "Students")</li>
                        <li>@Html.ActionLink("My Courses", "Index", "Courses")</li>
                    }


                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - S-Grades</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>